### ISSUE TITLE
Can't input polylines when creating an asset

### ISSUE THREAD

**Issue by andersonopt** [andersonopt/app-user-docs#1]
### Subject of the issue
When creating an asset, it only allows users to drop a pin or search for an address.  You can not input polylines or polygons.

### Your environment
* Anderson Opt v0.3.3-26

**Comment by jakebanderson321** [comment]
Polyline and polygon asset creation works. 

New Issue: When you type an address or lat/lng, the marker that gets dropped is stuck can't be drag and dropped to get precise location. It also doesn't disappear if you input another address. Another marker is simply added to the map.

**Comment by jakebanderson321** [comment]
New Issue: the identifying icons (blue for land, red for substation) are not added to created assets of that type when you use a polygon to create the boundary of the asset.

**Comment by jakebanderson321** [comment]
![screen shot 2018-10-16 at 12 40 18 pm](https://user-images.githubusercontent.com/13791320/47035991-0ca4b380-d141-11e8-9fcd-c85abc98cc19.png)
During creation process receive this error. Doesn't seem to affect anything but wanted to note.

Main issue on this is still that created assets without a marker drop don't have lat/lng coordinates associated with them so you can't search around the.

**Comment by eanderson4** [comment]
That makes sense, I can add that in before I release.

**Comment by eanderson4** [comment]
I wasn't able to reproduce but I should have fixed this specific error from occurring.

This seems like it is related to a new behavior with the address search function.  Now, when a user uses the address search, it will attempt to fill in parameters from googles search on address, city, state, name, and zip.

**Comment by eanderson4** [comment]
I didn't do a fix for requiring a marker drop on polygon assets.  I'm not sure how I want to approach yet so please inform client that for searches you will need to have a marker on the asset.
