### ISSUE TITLE
Multi substation searches

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#10]
### Feature Request
Allow users to search parcels and assets around multiple substations instead of just 1 substation.

**Comment by jakebanderson321** [comment]
Based on sales lead feedback, this feature has most potential to increase sales.

**Comment by eanderson4** [comment]
I put out a draft implementation of this feature on dev > v3.4-8 using the work from the multi transmission search.  Let me know of any issues you encounter.

**Comment by jakebanderson321** [comment]
Cool. I played with this earlier. 

The project sets up fine with 2 subs. However, the parcel search seems to still tie to a single sub. 

![image](https://user-images.githubusercontent.com/13791320/49325116-6b13ce80-f502-11e8-962b-4a20c32d1474.png)

![image](https://user-images.githubusercontent.com/13791320/49325117-7109af80-f502-11e8-8d7b-d69f10c4bd3a.png)

![image](https://user-images.githubusercontent.com/13791320/49325118-75ce6380-f502-11e8-8df8-d555c72e4657.png)

Note - I was in one of the Ohio demo teams using pre-loaded data. Don't think that should impact this, but let me know if I'm mistaken.

Also, as we aligned upon earlier this week, no need for you (Eric) to work on any Prospect in December and/or until after Strategen calms down given your crunched capacity. I am not requesting/expecting any more work on this or any other issue until after that time. I made the impact comment for future reference.

**Comment by jakebanderson321** [comment]
This did appear to work with live parcel data. not sure why that makes a difference. However, I did have an issue where the "Get Count" was 13 but it only returned 4 parcels. No errors in the console. 

https://v3-dev.andersonopt.com/team/demo-charlie/project/-LSc_9O-F17ZpPBgocF2

**Comment by eanderson4** [comment]
The local asset search for parcels is probably an outdated task.  The ones for transmission, substations, and plants should work with the multiwkt that is passed to the task.

Not sure on the 4/13 parcels, perhaps see if there are actual parcels that are being missed by the search if possible.  I'm not really sure why this would have an error like that.

**Comment by eanderson4** [comment]
Yah if you can find a case were a parcel is missed it by the search it will be easier to debug.  Otherwise it must be a bug with the get count functionality.

**Comment by jakebanderson321** [comment]
This project: https://v3-dev.andersonopt.com/team/demo-charlie/project/-LSc_9O-F17ZpPBgocF2

Doing a .5 mile radius with 100 acre minimum has a get count of 13 but only brings in the 4 parcels in the project.

**Comment by jakebanderson321** [comment]
Noticed that the distance calculation even in mult-sub projects seems to tie to just one of the subs rather than the sub that the parcel is nearby.

![image](https://user-images.githubusercontent.com/13791320/49386111-74f52780-f6e4-11e8-8f0a-39661596ef67.png)

**Comment by eanderson4** [comment]
v3.4-14 will have fix for minimum distance over all primaries and should be up soon.

**Comment by jakebanderson321** [comment]
Yep looks good.
