### ISSUE TITLE
Turn Edit Mode Off For Composite Polygons & Polygons copied from GIS layers

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#106]
### Subject of the issue
When you copy a feature from a GIS layer (e.g. wetlands), the polygon is saved with edit mode turned on. Edit mode is also turned on for polygons for composite polygons.

This can cause users to accidentally toggle and resize those polygons.

### Feature Request
Have the polygons start with edit mode off.

#### Your environment
3.5 chrome.

#### Steps to reproduce
Push Copy feature button from Wetland or floodplain layer. Create a composite polygon.

**Comment by eanderson4** [comment]
Perhaps this was fixed already, but I'm not replicated this on wetlands or flood hazard in latest version v0.4.0-21

**Comment by eanderson4** [comment]
Ping.  Let me know if there are issues still here

**Comment by jakebanderson321** [comment]
Good on 4.0-23. However follow up issue in:
