### ISSUE TITLE
Parcel Summary Closes When Adding Notes

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#117]
### Subject of the issue
When you try click into the "Notes" box of a parcel summary, the summary closes so that the user can't type their note.

### Bug Report
Fix this so that the summary stays open and users can add notes to parcels.

#### Your environment
V4.0-17
Chrome

#### Steps to reproduce
Click into the notes section of any parcel summary on any team.

#### Expected behaviour
Parcel summary stays open and user can type in notes

#### Actual behaviour
Parcel summary closes on notes click

**Comment by eanderson4** [comment]
I've added a button to close this window, it is small orange `x` and should pull to the right.  v0.4.0-20

**Comment by eanderson4** [comment]
This should be working in v4, let me know if issues

**Comment by jakebanderson321** [comment]
The functionality is working. 

I prefer the simply clicking on the top portion of the row as it is in v3 to keep things consistent. That "X" isn't very prominent. Users could easily miss it. However if there's a technical reason this is better, it is fine.

**Comment by eanderson4** [comment]
Not better, just was easier to implement.  I can look at making a better fix for this in the future

**Comment by eanderson4** [comment]
Alright, should be fixed now

**Comment by eanderson4** [comment]
in -26

**Comment by jakebanderson321** [comment]
Looks good
