### ISSUE TITLE
Clicking Rating Deletes Custom Filter

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#118]
### Subject of the issue
When a user adds a custom filter, the custom filter loses its affect as soon as the users tries to rate a parcel using the Star Ratings. While the full list of parcels comes back, the custom filter inaccurately displays as being turned on.

### Feature Request
Allow users to rate parcels that are in a filtered list.

### Bug Report
Custom filters are incorrectly removed when a user adds a star rating. 

#### Your environment
Chrome 4.0-17

#### Steps to reproduce
Add a custom filter to any parcel list. Click a star rating.

#### Expected behaviour
Star rating applies and the custom filter remains intact. 

#### Actual behaviour
The custom filter shows as being enabled, but the full list of parcels returns.

**Comment by eanderson4** [comment]
Fixed in v0.4.0-21, filtered list remains when project is updated.

**Comment by eanderson4** [comment]
This should be working in v4, let me know if there are issues

**Comment by jakebanderson321** [comment]
Looks good
