### ISSUE TITLE
Update Runtime Arguments when you copy a task

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#119]
### Subject of the issue
When we setup a new team, there are no tasks anymore. When you copy over the "Local Asset Search (Preloaded Data)" the arguments section of the Runtime tab doesn't update for the new team. We then go in and manually update.

Ultimately, this is a very small/easily updated quirk currently, but if we begin to have more complex tasks that require more extensive changes, this could become more laborious and cause a miss.

![image](https://user-images.githubusercontent.com/13791320/52719727-30073000-2f74-11e9-9de1-25497169cb2d.png)

### Feature Request
Have the arguments update in line with the team that they're copied to rather than copied from.

**Comment by eanderson4** [comment]
This is mostly solved by environmental variables but the old tasks didn't implement them.
You can use a variety of parameters in these arguments, such as `$team$` to denote current team

**Comment by eanderson4** [comment]
When I finish integrate Jim's work on #97 , I will make sure the tasks you copy will be ones that are team agnostic and don't have hardcoded team values

**Comment by eanderson4** [comment]
To finish my plan on how this works. 

With #97, we will be able to have a team that has these tasks loaded for each product.  
for example, 
team `ao-prospect-task` will have all tasks needed to run prospect, with no hardcoded tids

Then you will use mirror resources to copy all tasks to the new team.

Perhaps we can do a multiple team mirror if you need to update multiple teams at once.

**Comment by jakebanderson321** [comment]
Got it. This seems to make sense. We can disregard this as #97 appears to cover the functionality and remove the manual work/potential of missing a setup step.
