### ISSUE TITLE
Retain place in asset lists

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#123]
### Subject of the issue
Related to #122 

We have users who go into parcels' detail pages from the project detail page in order to update attributes on the parcel. 

Oftentimes, they may be on the 3rd or 4th page of the parcel list. 

However, when they return to the project page and the parcels step, they are back on the first page and have to navigate back through.

### Feature Request
Can you make it so that when a user is navigating through the parcel list on the project detail page that the list pagination they're on is retained so that they can return to the same spot when they navigate back after updating the parcel's details.

**Comment by jakebanderson321** [comment]
I've mentioned this specifically for the parcels list on the project detail page but have periodically heard similar comments about returning to the same page in lists in other use cases. 

It may make sense to just generally retain pagination location on all of our asset lists if the amount of work is similar. Priority on the parcel list though.

**Comment by eanderson4** [comment]
This is feasible.  A couple questions.

Do you just want this to persist during a specific session or should it persist between browser reloads and reopening the app?

Do these need to be accessible via url?  I.e. the user would want to copy the link and when shared it would bring to the same spot in the list.

It seems like the best approach might be to just persist between browser reloads and across all sessions and not have it do anything with the url.  This 'setting' would basically just be stored to the user and it would track the user page by team/table key.  This would allow pretty granular control over tracking locations in list i think and shouldn't be a lot of work at all

**Comment by jakebanderson321** [comment]
Got it. I'll follow up but my initial understanding is:

- Only need to save during a single session. Does this include simple refreshes (not sure if by browser reload you mean refresh or open/closing browser)? Since there are a couple areas where they need to refresh (geoanalysis for example), we should persist through that. However, I don't think we need to save between closing/reopening the app.

- No, I don't think this needs to be URL specific. The use case I'm aware of is just one person working through their process looking to speed it up.

Your suggested approach makes sense and seems to cover the use case. I haven't heard anything on needing a link.

**Comment by eanderson4** [comment]
Should be in latest release.  

- Only saves during current session.  
- Open steps now should stay open when going to and from a project
- Current spot in table should be saved by tid/table-key/project-id.  
    - It is implemented across the board for item tables so if this creates wierd behavior elsewhere we can add additional keys to the hash to fix.
    - ex. asset list page location should be saved as well

**Comment by jakebanderson321** [comment]
Looks good!
