### ISSUE TITLE
GIS Layers underneath parcel boundaries

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#124]
### Subject of the issue
GIS layers appear to now be underneath parcel polygons. You can't query the layer by clicking on a layer constraint that overlaps a parcel polygon.

### Feature Request
Allow users to click on GIS features that intersect other polygons.

### Bug Report
Can't query intersecting GIS features. You can replicate here: https://v3-dev.andersonopt.com/team/demo-alpha/asset/team~2Fdemo-alpha-land~2Fasset~2FOH-om_DEL_41724001027000

#### Your environment
Chrome 4.0-23

#### Steps to reproduce
Query GIS layer element that intersects parcel polygon

#### Expected behaviour
Display query information and copy feature box

#### Actual behaviour
Nothing

**Comment by eanderson4** [comment]
Until this is fixed, you can just remove the visibility on this and it will work

**Comment by eanderson4** [comment]
Ah i see, this is a regression.  I didn't realize this and the reference to other issue threw me off.  

This is actually related to the spiderfy change I made to help visualize the grid data sets that have a lot of overlapping markers.  Should be fixed now in 25

**Comment by jakebanderson321** [comment]
Ah gotcha. That makes sense on the confusion. 

In the future, I'll work to clearly call out regressions. 

Looks good!
