### ISSUE TITLE
Row color changes on-hover for selected assets (regression)

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#125]
### Subject of the issue
When an asset is selected (for example, parcels in project detail page for geo-analysis), the blue color disappears when a user's mouse hovers over the row. The text also goes white making data difficult to read.

See row two in image below. 

![image](https://user-images.githubusercontent.com/13791320/53113191-9d800700-3506-11e9-80f9-9a6b3ccb49ff.png)

In v3 the blue color persisted.

### Feature Request
Persist the blue color on hover similar to V3.

If the color change is intentional, at least keep the text in the columns dark so that it is more legible.

#### Your environment
Chrome
V4

#### Steps to reproduce
Select parcels in a project's "Parcel" step. Hover mouse over a row.

#### Expected behaviour
Blue color remains

#### Actual behaviour
Blue color goes away and the text stays white making it difficult to read the txt.

**Comment by eanderson4** [comment]
Should be fixed in -26

**Comment by jakebanderson321** [comment]
Looks good!
