### ISSUE TITLE
Asset map doesn't update when filters are applied

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#126]
### Subject of the issue
When a user adds a custom filter to the Asset List page, the list updates, but the map doesn't update. 

### Feature Request
Tie & update the asset map in line with the custom filter list

### Bug Report
The asset map doesn't update in line with custom filters.

#### Your environment
Chrome 4.0-30

#### Steps to reproduce
Add custom filter to "Asset List" page

#### Expected behaviour
Map should only display the assets that meet the filter criteria.

#### Actual behaviour
Map shows all of the assets.

**Comment by eanderson4** [comment]
fix on versin -31

**Comment by jakebanderson321** [comment]
All good. Forgot to close previously
