### ISSUE TITLE
Page Transition Issue

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#14]
### Subject of the issue
Occasionally, when I have change pages, the application gets stuck/crashes and presents the following error message.

![image](https://user-images.githubusercontent.com/13791320/47041924-a07d7c00-d14f-11e8-8d15-6b9c46b7a106.png)

### Bug Report
Fill the following out for a bug report.

#### Your environment
3.3-34

#### Steps to reproduce
It has been sporadic. Working to figure out which pages consistently trigger this issue.

#### Expected behaviour
Properly navigate to another page.

#### Actual behaviour
Application sticks and crashes

**Comment by eanderson4** [comment]
Just want to clean out old issues if they are not actionable.  I'm going to close this, let me know if you can recreate somehow and we can reopen.
