### ISSUE TITLE
Edit Parcel Rating From Map

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#148]
### Subject of the issue
When users click a parcel on the map, it displays the details such as rating, lot size and name. 

Allow users to adjust the rating from that info box rather than just display it.

### Feature Request
Allow users to adjust rating from parcel left click pop-up box.

![image](https://user-images.githubusercontent.com/13791320/53969169-e6ff5300-40bd-11e9-9e4f-f60e7c3d428b.png)

#### Your environment
4.0-39 Chrome

**Comment by eanderson4** [comment]
-47 allows user to update rating from map and also refreshes map style when done this way

**Comment by eanderson4** [comment]
just a note, the rating in the parcel list does not update and still requires a refresh, more to do there still

**Comment by jakebanderson321** [comment]
Looks great!

**Comment by jakebanderson321** [comment]
Good to know on autoshading from parcel list rating. totally fine.
