### ISSUE TITLE
Polygon Select Doesn't Work for Line Projects

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#152]
### Subject of the issue
When you do "Polygon Select" to select transmission lines for a project, the lines aren't selected as the points of interest for the project. 

### Bug Report
When you do the polygon select for line projects, nothing happens.

#### Your environment
4.0-31

#### Steps to reproduce
Create transmission line project. 
Do polygon select for select from existing substation.  

#### Expected behaviour
Lines in the polygon are selected

#### Actual behaviour
Lines are not selected

**Comment by eanderson4** [comment]
This should be fixed in -45

**Comment by jakebanderson321** [comment]
Looks good
