### ISSUE TITLE
Changing project types doesn't save as newly selected project type

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#153]
### Subject of the issue
When a user starts creating a project and they accidentally click one project type but then select a different project type, the project saves as the original project type. The points of interest they select also aren't saved, since they aren't the right asset type.

Users have to navigate away and back to the create project flow to properly choose the right point of interest.

### Bug Report
Users can't change project type in the create project flow.

#### Your environment
Chrome 4.0-44

#### Steps to reproduce
Click Create Project
Click "Select Project Type" for on project type
Click "Select Project Type" for a different project type and finish the create project flow

#### Expected behaviour
The project saves as the new project type and saves the selected asset as the point of interest

#### Actual behaviour
The project saves as the original project type and as such can't save the point of interest

**Comment by eanderson4** [comment]
whoops.  issue came about because we try to keep any parameters that have been entered into the project.  This accidentally saved the project type. 

should be fixed in  v-45

**Comment by jakebanderson321** [comment]
Looks good!
