### ISSUE TITLE
Ability to Filter on Specific Parcel

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#154]
### Subject of the issue / Context
Users want to be able to see the point of interest nearby a single parcel. 

(They've asked about saving point of interest data to a parcel's detail page, but since a parcels can be in multiple projects, this doesn't seem like the right approach as we've discussed.) 

Filtering on the project page seems like the right approach.

To filter for a single parcel, users have to find a parcel name, remember the name and then key it into a custom filter on the parcel name, which is cumbersome.

### Feature Request
Create a way on the project detail page to automatically filter on a specific parcel. 

This could be done by adding a checkbox in the parcel summary for "Filter on this Parcel." This could also maybe be a right click feature.

Feel free to come up with other ways to accomplish the goal of easily filtering on a specific parcel so that the project detail map updates, and it can be seen nearby the point of interest

**Comment by eanderson4** [comment]
in v45, have ability to filter selected assets just like you can remove selected assets.

to do this, you have to turn on edit mode.

let me know if this is sufficient

**Comment by jakebanderson321** [comment]
Looks great!
