### ISSUE TITLE
Copy drawing elements

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#16]
### Subject of the issue
It is cumbersome to create many elements with the same style.

### Feature Request
Allow copying map elements and allow editing to easily create similar drawing elements.

**Comment by eanderson4** [comment]
This is a follow up to issue  #6

**Comment by jimmullett** [comment]
Have a fix for this in issues/november

**Comment by jakebanderson321** [comment]
Looks Good.
