### ISSUE TITLE
Increase Map Size

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#17]
### Feature Request
Increase the size of the map on the Project Detail page. Consistent feedback that it is too small. Make the default the "Widened" map would be a good start.

Ideal future state would be option locking the map at top of of a user's screen be the map and have the bottom section with the Asset categories/"Steps" be scrollable so the project map and assets could be viewed at same time.

**Comment by jimmullett** [comment]
I have a fix for the "Widened" map would be a good start part of this ticket.  It is in the issues/november branch for the moment.  Let me know if I should also implement the ideal future state as described above.

**Comment by jakebanderson321** [comment]
Looks Good. Creates followup issue on project metrics.
