### ISSUE TITLE
User created assets are not found when doing polygon searches

### ISSUE THREAD

**Issue by andersonopt** [andersonopt/app-user-docs#2]
### Subject of the issue
When performing a polygon search, user created assets such as substations and lines are not found in the search.

**Comment by eanderson4** [comment]
How to subscribe to an event: https://docs.andersonopt.com/app/v3/events/#subscribe-to-an-event

On the Ohio Demo team, there is a task `Update Asset` that can be used for the event subscription to perform the backend synchronization that will fix the issue. 

Currently, the latest version of the task worker is not deployed on production, so this task doesn't connect with the production backend.  To test this, you will have to just create new assets and search for these ones versus expecting the existing ones.

I'll be working to promote the task worker this week as well.
