### ISSUE TITLE
Pointer shudders when hovering over GIS toggles

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#20]
### Subject of the issue
When you hover your mouse over the toggle switches in the Layer Management table, the pointer rapidly toggles back and forth between a mouse pointer and finger/press icon making it difficult to toggle the switches. It also toggles the tooltip on and off rapidly in line with the pointer toggling back and forth.

#### Your environment
This issue has been persistent in all versions.

#### Steps to reproduce
Hover mouse over layer toggle in layer management table.

#### Expected behaviour
Pointer turns to finger/click icon and remains stable so that when a user clicks their mouse the switch is enabled.

#### Actual behaviour
You must wiggle your mouse around and it ultimately stops the rapid toggling, and then you are able to click.

**Comment by jimmullett** [comment]
Have a fix for this in the issues/november branch.  There is still a touch of flickering as the pointer moves into the switch area but stabilizes in less than a second and is easily clickable.

**Comment by jakebanderson321** [comment]
Looks good.
