### ISSUE TITLE
Ability to create asset from project detail page

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#22]
### Feature Request
Create the ability to initiate a create asset flow from the proper "Step"/Asset Category in the project detail page.

This would operate similar to how the "Create Asset" flow currently works in the "Create Project" flow. 

In each asset category  dropdown (Transmission Line, Alternative sub, etc), have a link that when pressed initiates creating an asset of that type right in the project detail page. After completing, have it automatically added to that project.

**Comment by jimmullett** [comment]
Was able to get this one to happen via config.  Here's a sample config: https://v3-dev.andersonopt.com/config-edit/-LSHPLVebPixKDI9Ftdc?type=root

The modifications are in the Greenfield Substation project type.  An example of how parcels are modified: https://v3-dev.andersonopt.com/config-edit/-LSHPLVebPixKDI9Ftdc?type=project:greenfieldoff:land

Note the added select property of asset in the land config.  Using this config I was able to create new assets for each asset type in the project detail page.

**Comment by jakebanderson321** [comment]
Looks good - a couple follow ups that still exist: 

Mainly for the use case outlined above in #34. Also, the ability to create a land asset with a parcel boundary rather than just a pin drop.
