### ISSUE TITLE
Change polygon color in drawing menu inline with map drawing

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#23]
### Feature Request
In the "Drawing" menu, change the polygon's colors in line with the color they are on the map similar to how the shape currently reflects the actual shape

![image](https://user-images.githubusercontent.com/13791320/47188620-630b2100-d2fe-11e8-9780-fcf3cade9bfa.png)

#### MINIMAL priority

**Comment by eanderson4** [comment]
Fix in 3.4-10

**Comment by jakebanderson321** [comment]
Looks good. Closing
