### ISSUE TITLE
US Energy Mapper Not Working

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#29]
### Subject of the issue
The US Energy Mapper layer currently is not working. It gives the following console errors:

![image](https://user-images.githubusercontent.com/13791320/48087147-2d9e7880-e1c4-11e8-8d01-190496a6cbc2.png)

### Bug Report
Update energy mapper layer to work properly again.

#### Your environment
Chrome
3.4-2

#### Steps to reproduce
Turn on Energy Mapper layer

#### Expected behaviour
Layer should display

#### Actual behaviour
Loading map message displays and the layer stalls out.
Tell us what happens instead

**Comment by eanderson4** [comment]
Looks like they have a new version.

url: https://maps.eia.gov/arcgis/rest/services/USEnergyMappingSystem/20181011/MapServer/
