### ISSUE TITLE
Asset searches by owner and naming similarity filtering

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#3]
### Feature Request

Create the ability to search for land by owner name. 

Also create the ability to pull in parcels and have then have the parcels filter based upon a provided name keyword which collectively add up to a minimum total acreage threshold.

### Example

User wants to automatically identify parcels owned by the same land owner but potentially under different names. Ideally, they could submit 500 development acres with a minimum parcel acreage of 100. The software would then pull into AO. It would then automatically filter the parcels on name similarity to reach a total development acreage.

**Comment by eanderson4** [comment]
I started with a simple exact name match on 3 categories: owner, address name, mailaddress name

I went and did two report all searches
min-acres: 400 -> yielded 9 parcels
min-acres: 100 -> yielded 118 parcels

Using name match to group, we have
min-acres: 100, desired-acres: 400 -> yielded 36 parcels

Spreadsheet is attached in slack.

Seems like this would be a good first pass, we can improve from here if needed.

**Comment by eanderson4** [comment]
Here is an example I just ran

desired size: 300 acres

min-acres: 125 -> 31 parcels
min-acres: 300 -> 1 parcel

using new feature
min-acres: 125 + desired-size: 300 -> 5 parcels, 3 groups

![image](https://user-images.githubusercontent.com/5291870/47233409-de68e300-d38f-11e8-83e3-106cb01b3c6a.png)

**Comment by jakebanderson321** [comment]
Get Count task throws an error: 

![image](https://user-images.githubusercontent.com/13791320/47310498-f5f8d380-d5fc-11e8-95c6-b118450e2d96.png)

**Comment by jakebanderson321** [comment]
Running this query failed - no error message thrown.

![image](https://user-images.githubusercontent.com/13791320/47310610-3f492300-d5fd-11e8-9362-4e1ff1449dfb.png)

**Comment by jakebanderson321** [comment]
![image](https://user-images.githubusercontent.com/13791320/47311284-eb3f3e00-d5fe-11e8-9aa4-f5ca70977a4c.png)

![image](https://user-images.githubusercontent.com/13791320/47311296-f2fee280-d5fe-11e8-983f-faa58ec137cf.png)

![image](https://user-images.githubusercontent.com/13791320/47311307-f72b0000-d5fe-11e8-9f9c-9675c9cf9cdd.png)

**Comment by eanderson4** [comment]
Is this working properly now?

**Comment by jakebanderson321** [comment]
Looks good!
