### ISSUE TITLE
Multiple Project Parcels in the Same KML Export

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#30]
### Subject of the issue
Create the ability to include multiple parcels in a project in the same KML export. For example, include all parcels with the same owner in an export. 

### Feature Request
Here are a couple ways this could be accomplished:

- Update "Parcels" section map in line with custom filter
In this scenario, a user could do a custom filter. 

When they filter the parcel list, the map of the project parcels would update to show only the parcels that meet that criteria. For example, in the image below only 4 parcel boundaries would show

![image](https://user-images.githubusercontent.com/13791320/48099480-44a19280-e1e5-11e8-813b-b099349748ae.png)

- Select from parcels list
Another way to accomplish this would be simply click several parcels from a project's parcel list. After selecting there could be a few options:

One option would be "create combined parcel" - this button would create a land asset that is effectively the combination of all of them.

Another option would be to simply select them all then have a function to "export all" and they would all export into a single KML

Any of these seem sufficient, so go with whatever is easiest to build or would support other future features.

**Comment by jakebanderson321** [comment]
Yes, the edit button allows for exporting of all parcels. However, they want to export only the parcels of a selected owner or a filtered list.

So the map would need to update in line with the filter or have a way to specifically select which ones the user wants to export.

**Comment by eanderson4** [comment]
I'm pretty sure this happens in the 'parcel step' map pane

**Comment by eanderson4** [comment]
Ah yes, it appears it filters the view but it still shows up on the export.  This can be an easy fix then.

**Comment by eanderson4** [comment]
Sounds good, yah the map has been updating according to the filtered list.  There was a bug in the export that didin't filter these hidden items which I've fixed and is live on 3.4-4.

**Comment by eanderson4** [comment]
Pinging to see if this is working properly.

**Comment by jakebanderson321** [comment]
Looks good. Closing.
