### ISSUE TITLE
Turn a Polygon Copied from Parcel Layer into Parcel Asset & Save to Project

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#34]
### Subject of the issue
This is somewhat related to #15 

Users utilize the Parcel Layer in the Project Detail map to look for additional parcels to add to a project.

They click these parcels and select copy feature to add the drawing. 

However, this obviously doesn't create an actual parcel asset in the database which is saved to the project as it's just a drawing.

### Feature Request
Create the ability to turn a copied parcel drawing into a parcel asset and add it to the parcel list of the project that it was created within. 

Alternative method to get same result:
Now that #22 is being completed, you could have it where the assets in a project display in "Step 2" of the asset creation process from the project detail page. They could then do the parcel searching from here rather than the project detail page.

The first method seems cleaner/better UX but not sure if second method is easier to implement.

**Comment by eanderson4** [comment]
I would say your first method would fit best.  

I would put this functionality right next to the copy element that is coming soon.  So it would have options for

- Copy element
- Create asset from element. 

To create the asset, the main choice a user would have to make to get it created is what type it is.  I propose we keep this simple and make a simple dropdown that lists asset types, and then the create button.

The map element can emit this new asset to be captured and added to the project.  The user can navigate to this new asset to make any updates as necessary.  

When creating the asset, the element name and notes would go to name and description of asset and the geometry would be copied.  For polygons, an interior point marker should be created and added to lat long properties of the location of the asset.

**Comment by jakebanderson321** [comment]
Yes, I agree - the first method would be best, and I think it will be much cleaner. 

I like putting it right next to the copy element and making it a one click process. 

Ideally, this will also save the polygon outline to the asset as well so that it is also seen in the project detail and parcel list map. 

When you create a land asset with a marker then later add a polygon outline you can see it in the asset detail map but not the project maps

**Comment by jakebanderson321** [comment]
This is the feature that most commonly holds users back from being able to fully implement their desired project flow. 

Only feature that I've heard that is completely missing and can't really be backed into for users. Although ability to create parcels in the "Parcels" step is a great move in this direction.

**Comment by eanderson4** [comment]
A workflow to accomplish this is in v3.4-8 on dev.

Users can create assets from right click menu on map.

![image](https://user-images.githubusercontent.com/5291870/49324274-cedcce00-f4e7-11e8-8c76-73279a84926d.png)

Users can then copy the asset to the 'clipboard'
![image](https://user-images.githubusercontent.com/5291870/49324279-ec119c80-f4e7-11e8-8352-e9c150bb6254.png)

After copying an asset, if you are editting a step, you can show copied assets
![image](https://user-images.githubusercontent.com/5291870/49324291-0e0b1f00-f4e8-11e8-87ee-619a8cad1341.png)

Click the asset to add to step
![image](https://user-images.githubusercontent.com/5291870/49324298-267b3980-f4e8-11e8-9304-b3060c4f7ffe.png)

**Comment by jakebanderson321** [comment]
LOVE the UX of this. Fantastic job. Seems to be working nicely on my end. I will close issue.

Again, from here as we've talked about, any issue reports, I expect no work from you (Eric) until after Strategen - even if I label them user priority. I've actively communicated that near term development will be UX/UI related rather than feature related.
