### ISSUE TITLE
Save Column Ordering in Asset Tables

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#35]
### Subject of the issue
When you adjust the ordering of columns in an asset table (parcel table most important), the order is not saved on a refresh. The added metrics are saved, but they aren't in order.

Users often like to see things like buildable area close to lot size for comparison, but it often gets pushed to the side. Others like to easily see notes and same thing happens. 

### Feature Request
Save the table order when columns are added

This is a user request but lower prioritization

**Comment by eanderson4** [comment]
So I just tested, and it appears what is not saved is when columns are reordered.  

So you can test this as a fix until we can save reordering.

Drop columns and then readd them in the order you would like them. 

See if that works for you, it appears to work for my simple test.

**Comment by eanderson4** [comment]
So what is happening after looking at the code, the save mechanism is triggered when the size of the column list changes.

A fix for this issue *should be* relatively simple by changing the watch function trigger in the following code in block.util/item-table.controller

```js
    $scope.$watch(
        function() {
            return ctrl.current.length;
        },
        function(newVal, oldVal) {
            if (newVal !== oldVal) {
                log.debug('ItemTable : ColumnsChanged');
                log.debug(newVal, oldVal, ctrl.current);

                var serialize = _.map(ctrl.current, function(column) {
                    return _.pick(column, ['groupKey', 'parameterKey', 'name']);
                });
                //console.log('serialize', serialize);
                _.set(ctrl.userState, ctrl.tablePath, serialize);
                //console.log('userstate,', ctrl.userState);
                ctrl.userState.$save();
            }
        }
    );
```

**Comment by eanderson4** [comment]
The fix for this can cause some freezing issues, so I'm removing from release as there is a workaround by removing columns and then re add in the create order.

**Comment by jakebanderson321** [comment]
Totally fine. Very minimal with ability to add columns in order as desired
