### ISSUE TITLE
Custom Filtering for Project Attributes 

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#36]
### Subject of the issue
Users want the ability to custom filter on "Rating" and "Distance" (from point of interest). However, since these attributes are saved to a project rather than an asset it currently isn't possible.

Users want a way to easily see only good parcels on the project and parcel list maps. Also, they often may start with too large of a radius so they want a way to view only the parcels within a smaller radius, which would be accomplished by a distance custom filter.  

They want the view ability because they often have to present mappings of the ideal land to leadership internally and currently we don't have a good way to support that.

### Feature Request
Create custom filter for Ratings and Distance - or more generally, custom filters for project attributes.

**Comment by eanderson4** [comment]
This functionality had been extended to the exporter, so it was relatively easy to add it into the filter as well.

One note, I didn't do anything for handling units on the distance metric.  When you add the distance measure to the filter, you will see samples from it and that may give the user an idea of what units they are in.  It may take some work to get that in but this should help in the mean time.

![image](https://user-images.githubusercontent.com/5291870/49172994-b611c400-f2ff-11e8-9784-93f4ce3666b5.png)

**Comment by eanderson4** [comment]
Pinging to see if this is working properly.

**Comment by jakebanderson321** [comment]
Looks good. Ya, defaulting units to kilometers is fine for now. I'll create follow up issue for this. MINIMAL PRIORITY
