### ISSUE TITLE
Easily Style Multiple Parcels At Once

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#37]
### Subject of the issue
Similar to issue #36, users want an easy way to view their favor parcels in the Project Detail Map as well as the parcel list map. 

Aside from filtering on rating, this can be accomplished with styling / polygon design.

There are likely many ways to accomplish this. I've outlined ideas below but users don't seem to have a preference on the method. They just want the end result of differently styled polygons.

### Feature Request

1: Config Method
Similar to how we have styles that adjust for "Complete" "In Progress" etc grid assets, I imagine it'd be possible to create custom styling based upon star ratings. IE 3 stars turns a polygon green (or whatever color a user decides).

2. Apply Saved polygon styles to multiple parcels at once
Users can already save styles, but to apply them to a polygon, they must go into the drawing menu of each one and select it from the style list

![image](https://user-images.githubusercontent.com/13791320/49170827-9b8d1a00-f302-11e8-9933-55dc070c0d47.png)

You could create the ability to select multiple parcels/assets at once, select the style from the style list and have it apply to all of them.

This is a user request with lower prioritization.

**Comment by eanderson4** [comment]
There are two issues that are working to help this issue
Issue #46 adds a style selection menu to the right click button, so you no longer need to find the element below the map so applying styles should be substationally easier.
Issue #49 allows the style manager to style based on project attributes.  This would accomplish the use case of coloring the parcels based on a rating within the project.

Would that be sufficient for addressing this issue?

**Comment by jakebanderson321** [comment]
Yep, that should be more than sufficient.
