### ISSUE TITLE
Table headings out of line with columns

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#38]
### Bug Report
Sometimes the headings of asset tables get out of line with the columns underneath them. This seems to occur when adding/removing columns or reordering them, but I don't have an exact way to replicate.

![image](https://user-images.githubusercontent.com/13791320/49171037-34bc3080-f303-11e8-8e03-cdf44fdedca6.png)

MINIMAL PRIORITY - mainly calling out 

#### Your environment
 v0.3.4-5 and prior.

Chrome 

#### Steps to reproduce
Fiddle around with reordering and adding/removing columns from asset tables

#### Expected behaviour
Columns move and align with headings.

#### Actual behaviour
Columns and headings get out of line.

**Comment by eanderson4** [comment]
Is this still happening?  Is there a specific spot it occurs?  If we can't recreate, lets close this until there is something actionable.

**Comment by jakebanderson321** [comment]
It happens often, but I haven't ever taken the time to see what action causes that. I'll play around because I notice it in my demos, so it's likely something as I go through that flow. Give me until the end of the week to determine direct cause. If I can't determine, agree on closing for now.

**Comment by jakebanderson321** [comment]
I notice this when I do training with users. I think it may just be due to slowness of their system. I'll close until more specific info.
