### ISSUE TITLE
CloseCreate Asset Steps in Project Detail Page: #22 Follow Up

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#39]
### Subject of the issue

Follow up to #22 . 

Create asset works fine, but after clicking "Create Asset" all of the creation steps remain and the screen stays stagnant making it difficult to see that this worked.

This is compounded by the fact that the new parcel doesn't show until after a refresh.

![image](https://user-images.githubusercontent.com/13791320/49186389-1c134100-f32a-11e8-8e79-f14ba98cfcb5.png)

### Feature Request
Ideal: Collapse the steps so that they no longer show and trigger a refresh so that the table updates and displays the newly created parcel. 

Backup Option: At least collapse the steps to show the process is complete. Users can refresh on their own if need be.

**Comment by eanderson4** [comment]
Fix in 3.4-10

**Comment by jakebanderson321** [comment]
Looks good. Closing
