### ISSUE TITLE
Improve Layout for Project Details: #17 Follow Up

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#41]
### Subject of the issue
Issue #17 follow up. 

Now that "Widen Map" is the default, the actual project details hang awkwardly at the top of the screen with significant white space

![image](https://user-images.githubusercontent.com/13791320/49188058-081e0e00-f32f-11e8-9af2-59044fd1e88c.png)

### Feature Request
My initial thought would be to lay each metric horizontally in a single row. However, I frankly am open to anything that looks more uniform and better utilizes the blank space.

**Comment by jimmullett** [comment]
pushed a fix in the feature/project-detail branch

**Comment by jakebanderson321** [comment]
I like this look. Closing.
