### ISSUE TITLE
Parcel Attributes / Columns are Confusing

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#42]
### Subject of the issue

The metrics that we include for parcel data is confusing. There are duplicate titles for different attributes and the tooltips are non-specific

I realize some of this is directly from ReportAlls API, but we should work to provide better clarity and UX to the user. 

### Feature Request

1) There are duplicates - for example there are multiple "Names", "Address Line 1s", etc. We should adjust naming to add additional specificity and remove duplication. I.e. why is 1 name different than the other.

2) The tooltips when you hover over these are more about the web development syntax rather than what the attributes are. For example address line 1's tooltip is "The total string must be no longer than 64 characters for US addresses or 200 characters  for international addresses." The tooltip should describe what the metric actually is

### Prioritization

Low

**Comment by eanderson4** [comment]
For some reference on how these are set

in config

`parameter/addresss` and `parameter/mailladdress`
are primary fields for report all information.  Updating the descriptions in this config should update the tooltips.

ReportAll has two mail address which why there are duplicate fields.  One may be a tax address and one owner address or something.  

Here is reportall api documentation https://reportallusa.com/solutions/overlay/documentation/#available-filters

Looking at the results, it appears address is suppose to be the address of the property and mail address is the mailing address used in tax forms.

![image](https://user-images.githubusercontent.com/5291870/49318233-f36b8280-f4b4-11e8-92b3-1a1a318e90be.png)

**Comment by jakebanderson321** [comment]
Great to know on configs.

And yep - kenw they came from ReportAll. Just felt like there may be a way for us to improve the naming or optics somewhat. Again, don't see this as a major issue right now but wanted to make note.

**Comment by jakebanderson321** [comment]
Great to know on configs.

And yep - knew they came from ReportAll. Just felt like there may be a way for us to improve the naming or optics somewhat. Again, don't see this as a major issue right now but wanted to make note.

**Comment by eanderson4** [comment]
Perhaps you could take this one on @jakebanderson321 

If you goto the footer and click on the version number, and then click into detail, it will bring you to the config information.  Then, at the top right of the page, click into 'config list'.  Then click 'copy default'.    The new config will show up at the bottom, click into it and give it a name and description.  Then click 'activate' at the top of the page.  To update the parameters, click into parameters, then these parameters show up under 'address' and 'mailaddress'.    There click into the individual sets and you will see all these descriptions you reference.  Update as you see fit.  With the config active, it should update upon page refresh when using the application.

Then just let me know when your happy with the names and descriptions and ill merge with active config.

**Comment by jakebanderson321** [comment]
Made some basic tweaks. Thanks for the walkthrough on this. 

Created in "Renaming Parcel Attributes"

**Comment by eanderson4** [comment]
This config has been merged with master and should be in active config shortly (which is config all users run unless they have a custom activated like you just did to test/create this).
