### ISSUE TITLE
Swap Ordering of Project Details Map & Details

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#43]
### Subject of the issue
Issue #41 Follow Up. Overall, layout looks great. However, could we actually flip the map to be underneath the project stats and the parameters box?

![image](https://user-images.githubusercontent.com/13791320/49386380-09f82080-f6e5-11e8-8a38-84f7a3a7855b.png)

AKA the project stats and the tabbed box with Name, description, etc would be first then the map would be underneath in the image above. 

This will allow the map to be closest to the asset steps. Again, overall the page looks much improved, so I'd consider this to be a minimal priority. Maybe adjust as you're working on the parcel list propagating to the details map in December.

**Comment by eanderson4** [comment]
Fix in v3.4-13

**Comment by jakebanderson321** [comment]
I'd also put this above the map: 

![image](https://user-images.githubusercontent.com/13791320/49524048-9edb5500-f870-11e8-9626-d4d687ce81a1.png)

This will get the map as close to the asset steps as possible.

Minimum priority.

**Comment by eanderson4** [comment]
We can keep this open if you are still thinking there can be improvements to the layout.  Ideally we can keep the stats right next to the map as they are part of the summary component.  But we could do something different with the name parameters like put in the accordian or maybe adding a divider to give the summary its own space like so

![image](https://user-images.githubusercontent.com/5291870/49600366-46738880-f940-11e8-8119-34bd4625811b.png)

compared to orig

![image](https://user-images.githubusercontent.com/5291870/49600388-5723fe80-f940-11e8-95bd-e4f60994de11.png)

**Comment by jakebanderson321** [comment]
I'm comfortable closing for now to keep the issues clean. I think the new look is huge improvement already and we're in a good place where I'd put this is so far down priority list, it wouldn't be worth upgrading if/until we made another larger scale change.

I'll leave it up to you though but would not suggest spending time on it.
