### ISSUE TITLE
Bug on Copying Created Parcel from Map: #34 Follow Up

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#44]
### Subject of the issue
I got an error when trying to add a "created" and "copied" asset from the #34 flow into the parcel list.

### Bug Report
Here are the error messages. I get the first one when I click "Copy" in the right click menu. I get the second when I show the copied parcels in the parcel step.

![image](https://user-images.githubusercontent.com/13791320/49407128-3039b280-f71d-11e8-9c39-97ff0508b2ee.png)

I was working in this project: https://v3-dev.andersonopt.com/team/demo-charlie/project/-LSopDl21Mq7uriB6CI7

#### Your environment
Chrome 3.4-11

#### Steps to reproduce
What may be causing the issue: What was unique about this time rather than other times I have successfully gone through this flow is that this time I created the asset. Then I left the project and navigated to another part of the application. Then I went to do the "Copy" flow.

#### Expected behaviour
Parcel should load into parcel list

#### Actual behaviour
I receive the error message outlined above

**Comment by eanderson4** [comment]
This appears to be related to the close create dialog if an asset was created. It happens when no toggles have been used for [create a parcel or select an existing parcel].

Fix in v3.4-12 should be live soon

**Comment by jakebanderson321** [comment]
Yep this looks good.
