### ISSUE TITLE
Map - Add style selection to right click menu

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#46]
### Subject of the issue
Improve right click menu so the user doesn't need to use the edit element dialog below the map and can stay on the map.

### Feature Request
Allow users to select from predefined styles and apply them to the current item.  Additionally, have a toggle that allows the user to save the current style.  This will replicate the save style behavior in the element manager.

If a user wants to define a new style, they will still use the style form in the element manager to try and keep the right click menu as simple as possible.

**Comment by jimmullett** [comment]
Have a fix for this one in feature/product-detail

**Comment by jakebanderson321** [comment]
Style doesn't save on refresh. I am able to replicate this issues on this project: 

https://dev-build.andersonopt.com/master/team/demo-alpha/project/-LFzU0DGKF9dWoWEGvBN

Also, when a style is applied. Clicking clear style didn't remove the style.

**Comment by eanderson4** [comment]
Did you wait for the asset updated info box?

Clear element style will update the asset info, but the user has to refresh for style to be cleared.

**Comment by eanderson4** [comment]
Also make sure you have the latest version by doing a hard refresh.  This appears to work on my local machine.

**Comment by jakebanderson321** [comment]
Odd. Yes, I've done multiple hard refreshes. I've also been for the asset updated info box to pop up and disappear before refreshing.

I'm on 3.6-1 **Master**

https://dev-build.andersonopt.com/master

**Comment by eanderson4** [comment]
So can you outline more on what is happening.  

Does the asset update info box pop up?  
Does the asset get an updated style then?  
It is only on refresh that it clears away?  
Does this happen for both asset items and drawing items?
Does this happen when you use the element manager too and not just the right click menu?

**Comment by eanderson4** [comment]
The clear style sounds like it is the behavior i programmed as long as it gets removed after refresh.  Unfortunately it is hard to determine the default style for items after they have been restyled without a refresh without a major rework of the system.

**Comment by jakebanderson321** [comment]
Happy to walk through the specifics. I'll first answer your direct questions, then walk through my flow:

- Yes, when I apply a style, the asset updated pop up displays. I then wait until it is gone before doing a refresh
- Yes, the asset initially updates and displays the proper styling when I first apply it. 
- Yes, the styling only disappears after I refresh. It stays proper until that point.

- The styling disappears after a refresh when I both use the right click menu and apply a saved style as well as when I use the edit button, dropdown a parcel and manually add a style

**Comment by eanderson4** [comment]
My guess is some styling is overriding this, it appeared that one of your styles was saved as I saw it on my machine.  

Are you on any company right now?

What is your map style config for your user (found in user profile user map drop down)?

Can you adjust styling using individual style boxes versus applying a presaved style and it will save through refresh?

**Comment by eanderson4** [comment]
Does this happen for drawing items? Or just asset items?

**Comment by jakebanderson321** [comment]
- No, I'm not in a company. 

- My user map style config is blank
![image](https://user-images.githubusercontent.com/13791320/50243912-1b535500-0394-11e9-83ed-ab2e677646d0.png)

- I have tried both saved styles as well as manually keying in a value within the "Edit" tool box. This still doesn't save. 

- This appears toonly apply to asset items. When I draw a polygon in the project detail map and style it, the styling persists.

Specific Process: 

- Right click parcel from project detail map. Select style from the saved styles list.

![image](https://user-images.githubusercontent.com/13791320/50243617-370a2b80-0393-11e9-9287-5af34ef2c29f.png)
- I then wait until the "Asset Updated" box appears and then disappears.
- Refresh browser and the styling disappears

Same thing happens when I:

- Open edit box, dropdown parcel, and manually add styling

**Comment by jakebanderson321** [comment]
Since these error notes are for #53 , and this feature looks good, I am going to close.
