### ISSUE TITLE
Map - Allow layer toggle from the map interface

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#47]
### Subject of the issue
The layer and element manager attempt to use the same area below the map.  This can be confusing and inconvenient for turning on and off layers.  

### Feature Request
Allow users to toggle layers within the map using the right click menu when not on an asset.  Currently, there is a handler for right clicks and nothing happens when there is no asset or drawing in the click area. 

 Proposal is to have an info box that has a compact list of 
- layer name
- tags
- toggle

If a user wants to change the opacity or see the map legend, they will use the layer manager below the map.

**Comment by eanderson4** [comment]
In this menu, also allow the user to change the edit state of the map.

This will allow users to toggle edit and add/remove layers in full screen mode.

**Comment by jimmullett** [comment]
Have a fix for this in feature/project-detail.

**Comment by jakebanderson321** [comment]
Maybe I'm doing this wrong..? 

When I double right click on the project detail map in a random area (not on an asset or drawing element), it simply zooms out.

If I single right click, nothing happens. 

No errors, notes, etc in the Console.

Version 3.6-1 **Master**

**Comment by eanderson4** [comment]
The double click has to happen in 1 second.  I can try and increase the timeout to see if that is the case.  I changed from single right click since if you are trying to right click a item it can be annoying.

**Comment by eanderson4** [comment]
Actually, it doesn't appear to be working now.  I'll look into it

**Comment by eanderson4** [comment]
Actually, I take back my last comment, I was on a different dev branch.  This works for me on dev-build master.

**Comment by eanderson4** [comment]
It looks like so 
![image](https://user-images.githubusercontent.com/5291870/50252622-c3711a00-03a4-11e9-979e-651c03b43224.png)

**Comment by jakebanderson321** [comment]
- This feature works on asset list and project list maps, but it does not work on project detail map. I'm not sure why this would be different. There are no errors when I try using it on the project details map. 

- Layers turn on properly when I select them from the double right click menu, but when I toggle off a layer, it stays displayed on the map

**Comment by eanderson4** [comment]
Does it work on an asset detail page?  I'm really not sure what would cause that as it seems like it should be the same code path for these cases.

Which layer types don't get toggled off? 
Do the layers not toggle off in the regular menu?

**Comment by jakebanderson321** [comment]
Alright, I spent more time on this. It was also confusing me why it wasn't working. 

It appears that the double right click is operational in the project detail map as long as you are clicking outside of the asset search radiuses. If you click within the asset search radiuses on the project detail map it zooms out. 

I can replicate this on this project: https://dev-build.andersonopt.com/master/team/demo-alpha/project/-LFzU0DGKF9dWoWEGvBN

In that project if I double right click within the red circle, it zooms out. If I double click outside of it, the layer table pops up.

**Comment by jakebanderson321** [comment]
Layers now appear to be toggling on and off as they should using the on map layer manager

**Comment by eanderson4** [comment]
Ahh yes, that makes sense.  Any sort of item on the map hijacks the right click event.  I added a default right click event to the projects to be the double right click as layer menu.  I'm not sure if this is desired or not but feel free to test it out. 

It should be up on master soon.  I added more details to the version information on the footer, so you should see something that says "Add default right click handler to project" by the version tag.

**Comment by eanderson4** [comment]
Footer version info ex
![image](https://user-images.githubusercontent.com/5291870/50321666-3951b000-048f-11e9-9a37-44754cabf75e.png)

**Comment by eanderson4** [comment]
Now  shift + right click accesses the layer menu.
