### ISSUE TITLE
Map - Element manager in project page

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#48]
### Subject of the issue
In the project page, the element manager has a lot of choices for binding geometry to assets.  Limit this list to 3 at most.  It is primarily to be interacted with on the asset detail page.

![image](https://user-images.githubusercontent.com/5291870/49540449-6007c800-f88d-11e8-80f4-08106f854e1e.png)

In the future, perhaps a copy paste binding behavior may be possible in the future.

**Comment by jakebanderson321** [comment]
This seems sufficient.
