### ISSUE TITLE
Map - Style manager can handle extra info from projects

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#49]
### Subject of the issue
Currently, the style manager can only draw styles based upon attributes of an asset.  When an asset is attached to a project, its asset reference on the project can store additional details on that asset with respect to the given project, such as distance and rating.  Allow the style manager to use these values for styling the asset.

**Comment by jimmullett** [comment]
Have a fix for this in feature/project-detail.  Here's a couple sample styles for User Map Styles:

  - item: asset
    name: Highest Rating
    selector:
      get: step.land.asset.land
      property: rating
      value: 3
    style:
      fillColor: green
      fillOpacity: 0.3
      strokeColor: green
      strokeOpacity: 1
      strokeWeight: 3
  - item: asset
    name: Middle Rating
    selector:
      get: step.land.asset.land
      property: rating
      value: 2
    style:
      fillColor: yellow
      fillOpacity: 0.3
      strokeColor: yellow
      strokeOpacity: 1
      strokeWeight: 3
