### ISSUE TITLE
Map - Add query toggle to map layers

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#50]
### Subject of the issue
Currently, all layers are queried if possible and it can be confusing when displaying many layers.

### Feature Request
Add a toggle that is on by default (if the layer can be queried) when a layer is toggled on.  Have the query function respect this toggle when the map is clicked.

**Comment by eanderson4** [comment]
Fix for this on master. Improved syncing between two layer managers and added toggle for querying just on arc-layer, can add to other layers as necessary.

https://dev-build.andersonopt.com/master/

**Comment by jakebanderson321** [comment]
Functionality works well. However, our users often seem to miss/don't read the Tooltips.

Can we change the toggles to link buttons similar to the right-click style manager:
![image](https://user-images.githubusercontent.com/13791320/50241516-438b8580-038d-11e9-87ee-170e7dcd80d2.png)

Have the buttons be something like "Turn Off/On Layer" and "Enable/Disable Queries."  Ideally the wording would change based upon the current state (aka if layer on it'd say "Turn on Layer" )

**Comment by jakebanderson321** [comment]
Functionality is good though.

**Comment by eanderson4** [comment]
Fixed on master, should be live in > 5 minutes

**Comment by eanderson4** [comment]
I just changed checkbox for query layer has having two checkboxes was confusing.  The main checkbox I feel still make sense intuitively and takes up less space than with words where it becomes cluttered.

**Comment by jakebanderson321** [comment]
I like that logic. Good job. Looks good.

SUPPPER minor style tweak - sorry for being picky.

Capitalize to "Disable/Enable Query"
