### ISSUE TITLE
November Release Follow-Up

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#51]
### Subject of the issue
On prod version, the project stats don't have the new formatting like the do in dev version. Prod still has the significant white space.

Prod: 
![image](https://user-images.githubusercontent.com/13791320/49593878-41abd600-f93a-11e8-96e0-aba66cbc90ec.png)

Dev
![image](https://user-images.githubusercontent.com/13791320/49593868-3bb5f500-f93a-11e8-942b-bc10ed303e8b.png)

### Feature Request
Can up update to the dev version. Also, this may be personal preference but I think that it looks nicer with the stats above the parameter box rather than parameter box above the stats. So project page order of stats, parameters, map, asset steps. If you like stats under parameters, that's fine too.

**Comment by eanderson4** [comment]
What are the version numbers?  Are they the same?  I don't see this behavior in the prod version.

We can't have the name input box inbetween the stats and the map.  The stats and the map are part of the project summary and are forced to be together.

**Comment by jakebanderson321** [comment]
It was showing 3.5 but once I did a hard refresh it updated. must have been a cache. looks good.

Totally fine on proj summary

**Comment by eanderson4** [comment]
Ah yah, could have been a stylesheet cache maybe.
