### ISSUE TITLE
Copied Polygons Arbitrarily Change Style

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#52]
### Subject of the issue

**MINIMAL PRIORITY**
When you first copy a polygon from the parcel layer it has a blue boundary and is clear like parcels that you pull into a project.

![image](https://user-images.githubusercontent.com/13791320/49817952-317b6880-fd37-11e8-8821-ab56dc15abc0.png)

However, when you refresh or leave the page, the color automatically fills in red despite not changing the coloring.

![image](https://user-images.githubusercontent.com/13791320/49818004-4d7f0a00-fd37-11e8-8873-6b781ceb794f.png)

Can you get this to maintain the initial styling?

### Bug Report
Fill the following out for a bug report.

#### Your environment
Through 3.5

#### Steps to reproduce
Copy parcel from parcel layer. Leave project. Return to project.

#### Expected behaviour
Maintain initial styling.

#### Actual behaviour
Color changes to filled in color

**Comment by eanderson4** [comment]
Fix for this on master will be up in 5 minutes or so.

**Comment by jakebanderson321** [comment]
Looks good.
