### ISSUE TITLE
Map - Store individual asset styling

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#53]
### Subject of the issue
Asset styles are not saved.  You can only apply predefined styles to assets using selectors in the style service.

### Feature Request
Allow the saving of asset styles.  

The asset style can be stored directly on the asset such as
```json
{
  "rn":<>,
  "style":{},
   ...
}
```
The style object will likely have to modified some as it will need to map to the elements created by the location parameter of the asset.

When an amoitem is loaded that is an asset, it should check for this style tag, and if exists, it will apply that style.

One complication is how this will interact with the style service.  It seems to me, this style should override all other styles from the style service.  So two routes I see
- Place the application of this style after the style service has been applied (in case only some elements have styles, still want to run style service on elements).
- Inject this style as top priority into the style service,

**Comment by eanderson4** [comment]
This should be fixed on master https://dev-build.andersonopt.com/master/

**Comment by eanderson4** [comment]
Fix for this on master.  Improved syncing between two layer managers and added toggle for querying just on arc-layer, can add to other layers as necessary.

https://dev-build.andersonopt.com/master/

**Comment by jakebanderson321** [comment]
Example parcel where styling isnt saving: https://dev-build.andersonopt.com/master/team/demo-alpha/asset/team~2Fdemo-alpha~2Fasset~2Fra_39041_31642001071000

**Comment by jakebanderson321** [comment]
Looks good
