### ISSUE TITLE
Merge IDE branch into master for task creation

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#60]
### Subject of the issue
IDE branch needs to be merged with master and work done so it is useful in task creation.

**Comment by jimmullett** [comment]
Started this one off by merging the latest master into the feature/ide branch.  Resolved some conflicts, mostly in the side bar, and fixed a split.js ref in gulpfile.

**Comment by eanderson4** [comment]
Great thanks!  Even if it is not fully functioning I'd like to get into master so we can continue on main branch

**Comment by jimmullett** [comment]
It does look like the latest round of merging has broken a few things in the ide.  Here is a merge request for the final merge as I believe I don't have permission to do so.  https://gitlab.com/anderson-opt/ao-frontend/merge_requests/19
