### ISSUE TITLE
Asset Search Task Isn't Working

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#75]
### Subject of the issue
The asset search task isn't working. When the user clicks "run task" to find assets within a radius, the task queues but doesn't run.

![image](https://user-images.githubusercontent.com/13791320/50605490-098baa80-0e88-11e9-88b2-636053c0eb10.png)
 
There are no errors in the console. 

![image](https://user-images.githubusercontent.com/13791320/50605519-21632e80-0e88-11e9-8582-03142f4e2b74.png)

#### Your environment
3.5 Chrome

#### Steps to reproduce
Click "Run Task" on any asset step in a project. 

I have replicated across numerous teams and projects. Here is just one example: https://v3.andersonopt.com/team/demo-charlie/project/-LVEZLmSu0cQY8QZQHEv

**Comment by eanderson4** [comment]
Alright, I think i fixed it.

The worker had rebooted and picked up the wrong queue so there were no active workers.

**Comment by jakebanderson321** [comment]
Yep - looks good. Thanks!
