### ISSUE TITLE
Selecting Point of Interest Asset Stalls Machine

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#76]
### Subject of the issue
During the create project flow, selecting the primary asset can stall machines. 

When you select the asset, it gives the following error message, and there is a slight stall: 

![image](https://user-images.githubusercontent.com/13791320/50651736-ed504200-0f49-11e9-9653-8ef2af9a2716.png)

Normally, it just hangs for a second or two and then works properly for substation project. However, I have done training with  users and seen it occasionally crash their machines. 

The biggest issues occur with land projects - particularly land projects where users create a parcel during the create project flow.

### Feature Request
Give us information on what feature you are looking for.

### Bug Report
Browsers can crash when a user selects their project's point of interest.

#### Your environment
Through 3.5

#### Steps to reproduce
Create project. Select substation/line/land from map.

**Comment by jimmullett** [comment]
Think I found the fix for this, which is in the issue/76-select-point-of-interest branch.  The fix resolves the error message.  I wasn't able to reproduce the browser/machine crash so couldn't test that.

**Comment by eanderson4** [comment]
Ping, think this should be resolved.  I did one thing awhile back to try and ensure to stalls as well.

**Comment by jakebanderson321** [comment]
Yep, this is good now.
