### ISSUE TITLE
Mirror team resource

### ISSUE THREAD

**Issue by eanderson4** [andersonopt/app-user-docs#97]
### Subject of the issue
Currently, no good way to bulk copy resources from one team to another.

Use case:  Client setup requires the same set of assets for a given state.  Mirror from a team with latest data to new team to create new account.

### Feature Request
Create a sub-page on the admin page.  Allow user to select a 
- from team
- to team
- resource (use aolib, currently assets are most important)

Copy

Copy will retrieve list of assets from `from team`.  It will then run a rate-limitted create for each asset in the `to team`.

There are examples of copying items in the components.data/data-detail controller.  This example shows how to copy a resource with associated items.  For just the asset, we just need to run copy and not mirror associated.  I suppose it would be nice to have a uniform api for ResourceGeneral items to copy everything as well, it sure would make this page easier to implement in a general resource sense.

There is an example of rate limiting creates in components.scenario/s-run-instance.factory.

**Comment by eanderson4** [comment]
To finish this up, it will be useful to allow copying of more than just assets.  Here are my suggested resources to allow for copying as a first pass

- task
- scenario

(may be slightly different than assets, I don't think I have copy implemented in ResourceSimple)
- teamConfig (r-team-config)
- teamMap (r-team-map)

**Comment by jimmullett** [comment]
There is an upgrade for this in issue/97-mirror-team-resource (ao-frontend).  Also upgraded ao-lib and used the feature/admin branch.

Here's some things of note:
- When running anything I get many 403 errors that look like `vendor.js:64981 GET https://energy-opt-green-.firebaseio.com/.lp?start=t&ser=81141400&cb=33&v=5 net::ERR_ABORTED 403 (Forbidden)`
- The copy will not check for duplicates and multiple copies will create duplicate resources
- Was able to get resource maps and config to copy but wasn't quite sure how to test via the ui
- Tested copying team 'RMI Test - Beta' to Jim test
- Tested copying team 'Ohio Demo' to 'Jim Test' - this one had a lot of .set permission denied errors though the copy still completes.
- There could be more verbose feedback during copy - for now I was using the console and was in the team being copied to, both of which help with feedback
- Some code was moved into ao-lib and admin service but there is more refactoring that could be done to get more into ao-lib and/or admin service (or some other service).
- The one team I kept copying to is getting pretty full.  Would be good to be able to create new teams and add members or have a few other test teams.
- Several times during working on this one I was wish wishing I had direct access into a test db.  Is this a possibility?

I think that is it, let me know if you want me to add any more upgrades

**Comment by eanderson4** [comment]
Thanks for the notes on this.  I just did some basic testing on this and it looks good.  We can do follow ups after standing up a dev database so it is easier to troubleshoot.

- I think you should be able to create a team in the admin section, let me know if that is not working.
